const photoStyles=document.createElement('link');photoStyles.rel='stylesheet';photoStyles.href='photos.css';document.head.append(photoStyles);
const heroImage=document.querySelector('.hero>img');if(heroImage)heroImage.src='assets/crocodilian-hero.png';
const editorialStyles=document.createElement('link');editorialStyles.rel='stylesheet';editorialStyles.href='editorial.css';document.head.append(editorialStyles);
const headStyles=document.createElement('link');headStyles.rel='stylesheet';headStyles.href='head-comparison.css';document.head.append(headStyles);
const distinctStyles=document.createElement('link');distinctStyles.rel='stylesheet';distinctStyles.href='distinct.css';document.head.append(distinctStyles);
const extinctStyles=document.createElement('link');extinctStyles.rel='stylesheet';extinctStyles.href='extinct.css';document.head.append(extinctStyles);
const extinctSection=document.createElement('section');extinctSection.className='section extinct';extinctSection.id='extinct';extinctSection.innerHTML=`<div class="extinct-intro"><p class="chapter">DEEP TIME / EXTINCT &amp; EXTRAORDINARY</p><h2>Before the<br><em>living 26.</em></h2><p class="lead">The croc family tree once experimented with giants, broad-mouthed gulp feeders, and long-snouted river hunters. Some below are true crocodilians; others are older croc-line relatives outside the living order.</p></div><div class="deep-time" role="list"><article role="listitem"><div class="era">EARLY CRETACEOUS <b>≈112 MYA</b></div><div class="fossil-name"><span>01</span><h3>Sarcosuchus</h3><i>Sarcosuchus imperator</i></div><p>A massive African crocodyliform—not a true crocodilian—with an elongated snout and a swollen boss at its tip. Fossils suggest a slow-growing animal that could keep growing for decades.</p><strong class="scale">UP TO ≈9–9.5 M (29.5–31.2 FT)</strong></article><article role="listitem"><div class="era">LATE CRETACEOUS <b>≈82–73 MYA</b></div><div class="fossil-name"><span>02</span><h3>Deinosuchus</h3><i>Deinosuchus spp.</i></div><p>The “terror crocodile” lived along North America’s ancient inland seaway. Some individuals reached roughly 8–10 meters (26.2–32.8 feet) by extending ordinary reptilian growth over many years.</p><strong class="scale">≈8–10 M (26.2–32.8 FT)</strong></article><article role="listitem"><div class="era">MIOCENE <b>≈13–5 MYA</b></div><div class="fossil-name"><span>03</span><h3>Mourasuchus</h3><i>Mourasuchus spp.</i></div><p>A giant South American caiman with an extraordinarily wide, flattened skull and comparatively delicate jaws—likely adapted for gulp-feeding on small prey.</p><strong class="scale">THE DUCK-FACED CAIMAN</strong></article><article role="listitem"><div class="era">LATE MIOCENE <b>≈8–5 MYA</b></div><div class="fossil-name"><span>04</span><h3>Purussaurus</h3><i>Purussaurus brasiliensis</i></div><p>A true giant caiman of proto-Amazonian wetlands. One published model estimated about 12.5 meters (41 feet) long and a sustained bite force near 69,000 newtons.</p><strong class="scale">EST. ≈12.5 M (41 FT)</strong></article></div><aside class="deep-note"><b>A NOTE ON THE WORD “CROCODILE”</b><p>Popular accounts often call every crocodile-shaped fossil a crocodile. Crocodyliforms form a much larger evolutionary branch; Crocodilia is the smaller crown group containing the living species and their closest extinct relatives.</p></aside>`;
document.querySelector('.anatomy')?.before(extinctSection);const extinctImageStyles=document.createElement('link');extinctImageStyles.rel='stylesheet';extinctImageStyles.href='extinct-images.css';document.head.append(extinctImageStyles);const extinctImages=[['sarcosuchus.png','Skeletal reconstruction of Sarcosuchus imperator','LiterallyMiguel / CC BY-SA 4.0'],['deinosuchus.png','Life reconstruction of Deinosuchus hatcheri','Connor Ashbridge / CC BY-SA 4.0'],['mourasuchus.jpg','Scientific size reconstruction of Mourasuchus atopus','Armin Reindl / CC BY-SA 4.0'],['purussaurus.png','Life reconstruction of Purussaurus','LiterallyMiguel / CC BY 4.0']];document.querySelectorAll('.deep-time article').forEach((article,i)=>{const [file,alt,credit]=extinctImages[i],figure=document.createElement('figure');figure.innerHTML=`<img src="assets/extinct/${file}" alt="${alt}" loading="lazy" decoding="async"><figcaption>Reconstruction: ${credit}</figcaption>`;article.querySelector('.era').after(figure)});const extinctNav=document.createElement('a');extinctNav.href='#extinct';extinctNav.textContent='Extinct';document.querySelector('header nav a[href="#future"]')?.before(extinctNav);
const addedExtinct=`<article role="listitem"><div class="era">LATE CRETACEOUS <b>≈100–94 MYA</b></div><figure><img src="assets/extinct/kaprosuchus.png" alt="Life reconstruction of Kaprosuchus saharicus" loading="lazy" decoding="async"><figcaption>Reconstruction: LiterallyMiguel / CC0</figcaption></figure><div class="fossil-name"><span>05</span><h3>Kaprosuchus</h3><i>Kaprosuchus saharicus</i></div><p>The “boar croc” of ancient Niger carried enlarged, tusk-like teeth and a reinforced snout. It was a crocodyliform outside true Crocodilia, known from a spectacular skull.</p><strong class="scale">THE BOAR CROC</strong></article><article role="listitem"><div class="era">LATE CRETACEOUS <b>≈100–94 MYA</b></div><figure><img src="assets/extinct/stomatosuchus.png" alt="Scientific skull drawing of Stomatosuchus inermis" loading="lazy" decoding="async"><figcaption>Original fossil drawing: Ernst Stromer / Public domain</figcaption></figure><div class="fossil-name"><span>06</span><h3>Stomatosuchus</h3><i>Stomatosuchus inermis</i></div><p>This Egyptian crocodyliform had an extraordinarily long, broad and flattened skull. Its only known specimen was destroyed during the bombing of Munich in 1944, leaving Stromer’s drawings as vital evidence.</p><strong class="scale">THE LOST FOSSIL</strong></article><article role="listitem"><div class="era">HOLOCENE <b>BRONZE-AGE CHINA</b></div><figure><img src="assets/extinct/hanyusuchus.jpg" alt="Life reconstruction of Hanyusuchus sinensis" loading="lazy" decoding="async"><figcaption>Reconstruction: Hikaru Amemiya / CC BY 4.0</figcaption></figure><div class="fossil-name"><span>07</span><h3>Hanyusuchus</h3><i>Hanyusuchus sinensis</i></div><p>A long-snouted gharial relative that survived beside people in southern China. Archaeological remains bearing cut marks point toward human conflict and a remarkably recent extinction.</p><strong class="scale">SURVIVED INTO HISTORY</strong></article><article role="listitem"><div class="era">HOLOCENE <b>MADAGASCAR</b></div><figure><img src="assets/extinct/voay.jpg" alt="Skull reconstruction of the extinct horned crocodile Voay robustus" loading="lazy" decoding="async"><figcaption>Photograph: Wikimedia Commons / reusable license</figcaption></figure><div class="fossil-name"><span>08</span><h3>Voay</h3><i>Voay robustus</i></div><p>Madagascar’s stout “horned” crocodile survived into the recent past. Ancient DNA places it as a close sister lineage to living true crocodiles rather than among dwarf crocodiles.</p><strong class="scale">THE HORNED CROCODILE</strong></article>`;document.querySelector('.deep-time')?.insertAdjacentHTML('beforeend',addedExtinct);
document.querySelector('.deep-time article:last-child figcaption').textContent='Photograph: Ghedoghedo / Public domain';
const comparisonHeads=[
  ['.alligator-line','assets/species/black-caiman.jpg','Broad head of a black caiman','Black caiman · broad U-shaped snout'],
  ['.crocodile-line','assets/species/nile-crocodile.jpg','Head of a Nile crocodile with jaws open','Nile crocodile · tapered V-shaped snout'],
  ['.gharial-line','assets/species/gharial.jpg','Head of a gharial showing its long narrow jaws','Gharial · extremely slender jaws']
];
comparisonHeads.forEach(([selector,src,alt,caption])=>{const shape=document.querySelector(`${selector} .snout-shape`);if(!shape)return;const figure=document.createElement('figure');figure.className='head-photo';figure.innerHTML=`<img src="${src}" alt="${alt}"><figcaption>${caption}</figcaption>`;shape.replaceWith(figure)});
const favicon=document.createElement('link');favicon.rel='icon';favicon.type='image/jpeg';favicon.href='assets/species/saltwater-crocodile.jpg';document.head.append(favicon);
const mapStyles=document.createElement('link');mapStyles.rel='stylesheet';mapStyles.href='range-map.css';document.head.append(mapStyles);
const satelliteStyles=document.createElement('link');satelliteStyles.rel='stylesheet';satelliteStyles.href='satellite-map.css';document.head.append(satelliteStyles);
const statusStyles=document.createElement('link');statusStyles.rel='stylesheet';statusStyles.href='status-readable.css';document.head.append(statusStyles);
const mapScript=document.createElement('script');mapScript.src='range-map.js';mapScript.defer=true;document.head.append(mapScript);
const species=[
['American alligator','Alligator mississippiensis','Alligatoridae','Southeastern United States','4.6 m'],['Chinese alligator','Alligator sinensis','Alligatoridae','Lower Yangtze basin, China','2.2 m'],['Spectacled caiman','Caiman crocodilus','Alligatoridae','Central and northern South America','2.7 m'],['Broad-snouted caiman','Caiman latirostris','Alligatoridae','Eastern and central South America','3.5 m'],['Yacare caiman','Caiman yacare','Alligatoridae','Central South America','3 m'],['Black caiman','Melanosuchus niger','Alligatoridae','Amazon basin','5 m+'],["Cuvier’s dwarf caiman",'Paleosuchus palpebrosus','Alligatoridae','Northern and central South America','1.7 m'],['Smooth-fronted caiman','Paleosuchus trigonatus','Alligatoridae','Amazon and Orinoco basins','2.3 m'],
['West African slender-snouted crocodile','Mecistops cataphractus','Crocodylidae','West Africa','4 m'],['Central African slender-snouted crocodile','Mecistops leptorhynchus','Crocodylidae','Central Africa','4 m'],['Dwarf crocodile','Osteolaemus tetraspis','Crocodylidae','West and Central Africa','1.9 m'],['American crocodile','Crocodylus acutus','Crocodylidae','Florida, Caribbean, and tropical Americas','5 m+'],['Osborn’s dwarf crocodile','Osteolaemus osborni','Crocodylidae','Congo Basin, Central Africa','1.9 m'],['Orinoco crocodile','Crocodylus intermedius','Crocodylidae','Orinoco basin','5 m+'],['Freshwater crocodile','Crocodylus johnstoni','Crocodylidae','Northern Australia','3 m'],['Philippine crocodile','Crocodylus mindorensis','Crocodylidae','Philippines','3 m'],["Morelet’s crocodile",'Crocodylus moreletii','Crocodylidae','Mexico, Belize, and Guatemala','4.5 m'],['Nile crocodile','Crocodylus niloticus','Crocodylidae','Sub-Saharan Africa','5.5 m+'],['New Guinea crocodile','Crocodylus novaeguineae','Crocodylidae','Northern New Guinea','3.5 m'],['Mugger crocodile','Crocodylus palustris','Crocodylidae','Indian subcontinent and Iran','5 m'],['Saltwater crocodile','Crocodylus porosus','Crocodylidae','South and Southeast Asia to Australia','6.3 m+'],['Cuban crocodile','Crocodylus rhombifer','Crocodylidae','Cuba','3.5 m'],['Siamese crocodile','Crocodylus siamensis','Crocodylidae','Mainland Southeast Asia and Indonesia','4 m'],['West African crocodile','Crocodylus suchus','Crocodylidae','West and Central Africa','4 m'],
['Gharial','Gavialis gangeticus','Gavialidae','Northern Indian subcontinent','6 m'],['False gharial','Tomistoma schlegelii','Gavialidae','Malay Peninsula, Borneo, and Sumatra','5 m']];
species.forEach(s=>{const match=s[4].match(/^([\d.]+) m(\+)?$/);if(match){const feet=Number((Number(match[1])*3.28084).toFixed(1)),plus=match[2]||'';s[4]=`${match[1]} m${plus} (${feet} ft${plus})`}});
const facts={Alligatoridae:'Alligators and caimans combine powerful jaws with remarkable parental care, guarding nests and escorting hatchlings.',Crocodylidae:'True crocodiles include freshwater specialists, coastal travelers, forest dwellers, and the largest living reptiles.',Gavialidae:'The two living gavialids use elongated jaws for rapid, low-drag strikes in rivers and swamp forests.'};let family='all';const grid=document.querySelector('#grid'),search=document.querySelector('#search'),results=document.querySelector('#results'),dialog=document.querySelector('#profile'),body=document.querySelector('#profile-body');
const redList=[['LC','Least Concern'],['CR','Critically Endangered'],['LC','Least Concern'],['LC','Least Concern'],['LC','Least Concern'],['LC','Least Concern'],['LC','Least Concern'],['LC','Least Concern'],['CR','Critically Endangered'],['NE','Not Assessed'],['VU','Vulnerable'],['VU','Vulnerable'],['NE','Not Assessed'],['CR','Critically Endangered'],['LC','Least Concern'],['CR','Critically Endangered'],['LC','Least Concern'],['LC','Least Concern'],['LC','Least Concern'],['VU','Vulnerable'],['LC','Least Concern'],['CR','Critically Endangered'],['CR','Critically Endangered'],['NE','Not Assessed'],['CR','Critically Endangered'],['EN','Endangered']];
function slug(name){return name.toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function render(){const q=search.value.toLowerCase().trim(),shown=species.map((s,i)=>({s,i})).filter(({s})=>(family==='all'||s[2]===family)&&s.join(' ').toLowerCase().includes(q));results.textContent=`Showing ${shown.length} of ${species.length} species`;grid.innerHTML=shown.length?shown.map(({s,i})=>`<button class="card" data-i="${i}" aria-label="Open ${s[0]} profile"><img src="assets/species/${slug(s[0])}.jpg" alt="${s[0]}" loading="lazy" decoding="async"><span class="card-copy"><small>${String(i+1).padStart(2,'0')} / ${species.length}</small><small class="family">${s[2]}</small><h3>${s[0]}</h3><i>${s[1]}</i><span class="status status-${redList[i][0].toLowerCase()}">${redList[i][0]} · ${redList[i][1]}</span><p>${s[3]}</p><span class="arrow">↗</span></span></button>`).join(''):'<p class="empty">No species surfaced. Try a broader search.</p>'}document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelector('.active').classList.remove('active');b.classList.add('active');family=b.dataset.filter;render()});search.oninput=render;grid.onclick=e=>{const card=e.target.closest('[data-i]');if(!card)return;const index=Number(card.dataset.i),s=species[index];body.innerHTML=`<article class="profile"><img class="profile-photo" src="assets/species/${slug(s[0])}.jpg" alt="${s[0]}"><small>${s[2]} · SPECIES ${String(index+1).padStart(2,'0')}</small><h2 id="profile-title">${s[0]}</h2><p class="latin">${s[1]}</p><p class="profile-status status status-${redList[index][0].toLowerCase()}">${redList[index][0]} · ${redList[index][1]} on the IUCN Red List</p><dl><div><dt>RANGE</dt><dd>${s[3]}</dd></div><div><dt>MAXIMUM LENGTH</dt><dd>${s[4]}</dd></div></dl><p>${facts[s[2]]}</p><p class="status-note">NE means Not Assessed: IUCN has not assigned a global extinction-risk category to this taxon.</p></article>`;dialog.showModal()};document.querySelector('.close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};render();
